# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Главная
      path: homepage
    - label: Портфолио
      path: homepage
    - label: О нас
      path: homepage
    - label: До и после
      link: homepage
    - label: Видео Журнал
      link: homepage
    - label: Услуги
      link: homepage
    - label: Цены
      link: homepage
    - label: Мастер-классы
      link: homepage
    - label: Контакты
      link: homepage
footer:
    - label: Кафе, рестораны и т.д.
      path: homepage
    - label: Современные
      path: homepage
    - label: Прованс
      path: homepage
    - label: Классические
      path: homepage
rights:
    - label: Пользовательское соглашение
      path: homepage
    - label: Политика обработки персональных данных
      path: homepage
